{ ... }: {

  imports = [
    # Generated by nixos-generate-config; machine-specific (disk layout).
    ./nixos-hardware.nix
    ../modules/common/packages.nix
    ../modules/common/nix.nix
    ../modules/linux/default.nix
  ];

  # Manage user dotfiles (e.g. opencode config) declaratively.
  home-manager.useGlobalPkgs = true;
  home-manager.useUserPackages = true;
  # Preserve pre-existing files before Home Manager replaces them.
  home-manager.backupFileExtension = "backup";
  home-manager.users.metru = {
    imports = [
      ../modules/common/home.nix
      ../modules/linux/home.nix
    ];
  };

  # The platform the configuration will be used on.
  nixpkgs.hostPlatform = "x86_64-linux";

  # Bootloader.
  boot.loader.systemd-boot.enable = true;
  boot.loader.efi.canTouchEfiVariables = true;

  # System name, matching the flake output name (nixos).
  networking.hostName = "nixos";

  # Set your time zone.
  time.timeZone = "America/New_York";

  # Used for backwards compatibility, please read the changelog before changing.
  # $ nixos-rebuild changelog
  system.stateVersion = "26.05";
}
